FROM ubuntu

RUN apt-get update -y
RUN apt-get install -y net-tools
RUN apt-get install -y iputils-ping
RUN apt-get install -y vim
RUN apt-get install -y tcpdump
RUN apt-get install -y cmake
RUN apt-get install -y g++

WORKDIR /root
