FROM ubuntu

RUN apt update -y
RUN apt install -y net-tools
RUN apt install -y iputils-ping
RUN apt install -y vim
RUN apt install -y tcpdump
RUN apt install -y cmake
RUN apt install -y g++

WORKDIR /root
